server:
  port: 20000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth-server

  thymeleaf:
    cache: false
  redis:
    host: 192.168.30.100
    port: 6379
  session:
    store-type: redis
    timeout: 30m