spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-who
      access-key: LTAI5t6xwUWhwjUDB7oipamq
      secret-key: TUPEbfSLgMTQMTU6RBLYMKoDcR5RO5
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        tplid: TPL_0000
        appcode: 19a2e16c1f304b49bc1a23a7cd1d847f
server:
  port: 30000